sonar.projectKey=eco-trail
sonar.projectName=ecotrail
sonar.host.url=http://localhost:9000

sonar.token=squ_c91d9041cba6eca35ca5b56ef0a2a686a0789145

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml